/**
 * StyleSheet for the send screen (app/wallet/send.tsx). Confirmation-modal
 * styles live with SendConfirmationModal.
 */

import { StyleSheet } from 'react-native';

import { type Theme } from '@/theme/ThemeProvider';

export function makeSendScreenStyles({ colors, fonts }: Theme) {
  return StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  scrollView: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  pasteButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.hairlineStrong,
    backgroundColor: colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pasteButtonSpacer: {
    width: 44,
    height: 44,
  },
  recipientActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  recipientActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.hairlineStrong,
    backgroundColor: colors.surfaceElevated,
  },
  recipientActionText: {
    color: colors.text,
    fontSize: 14,
    fontFamily: fonts.ui,
  },
  resolvedRecipientCard: {
    gap: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.hairlineStrong,
    backgroundColor: colors.accentWash,
    padding: 12,
  },
  resolvedRecipientTitle: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 18,
    fontFamily: fonts.title,
  },
  resolvedRecipientText: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 18,
    fontFamily: fonts.ui,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.bg,
  },
  backButton: {
    padding: 8,
  },
  backButtonSpacer: {
    width: 40,
    height: 40,
  },
  headerTitle: {
    fontSize: 20,
    color: colors.text,
    fontFamily: fonts.title,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 28,
    gap: 18,
  },
  introBlock: {
    gap: 8,
  },
  screenTitle: {
    fontSize: 30,
    lineHeight: 34,
    color: colors.text,
    fontFamily: fonts.title,
  },
  screenSubtitle: {
    fontSize: 15,
    lineHeight: 21,
    color: colors.textMuted,
    fontFamily: fonts.ui,
  },
  card: {
    backgroundColor: colors.surfaceElevated,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.hairlineStrong,
    padding: 18,
    gap: 12,
  },
  label: {
    fontSize: 14,
    color: colors.textMuted,
    fontFamily: fonts.ui,
  },
  networkText: {
    fontSize: 18,
    color: colors.text,
    marginBottom: 8,
    fontFamily: fonts.title,
  },
  helper: {
    fontSize: 12,
    color: colors.textMuted,
    lineHeight: 18,
    fontFamily: fonts.ui,
  },
  recipientPill: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: colors.surface,
  },
  recipientPillText: {
    color: colors.text,
    fontSize: 12,
    fontFamily: fonts.ui,
  },
  fieldIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    backgroundColor: colors.surfaceElevated,
    borderWidth: 1,
    borderColor: colors.hairlineStrong,
    borderRadius: 18,
    padding: 16,
    fontSize: 16,
    color: colors.text,
    fontFamily: fonts.ui,
  },
  recipientInput: {
    minHeight: 60,
  },
  amountField: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 12,
    backgroundColor: colors.surfaceElevated,
    borderWidth: 1,
    borderColor: colors.hairlineStrong,
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 18,
  },
  amountFieldFocused: {
    borderColor: colors.accent,
    shadowColor: colors.accent,
    shadowOpacity: 0.14,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  amountInput: {
    flex: 1,
    minWidth: 120,
    minHeight: 72,
    fontSize: 34,
    lineHeight: 40,
    fontFamily: fonts.title,
    borderWidth: 0,
    backgroundColor: 'transparent',
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  amountTokenPill: {
    maxWidth: '100%',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: colors.surface,
  },
  amountTokenText: {
    color: colors.text,
    fontSize: 14,
    fontFamily: fonts.title,
  },
  quickButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 12,
  },
  quickButton: {
    flex: 1,
    minWidth: 84,
    backgroundColor: colors.surfaceElevated,
    borderWidth: 1,
    borderColor: colors.hairlineStrong,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 18,
    alignItems: 'center',
    minHeight: 52,
  },
  quickButtonSelected: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  quickButtonText: {
    fontSize: 14,
    color: colors.text,
    fontFamily: fonts.ui,
  },
  quickButtonTextSelected: {
    color: colors.onAccent,
  },
  mainSendButton: {
    backgroundColor: colors.accent,
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 32,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 60,
    alignSelf: 'stretch',
  },
  mainButtonWrap: {
    marginTop: 2,
  },
  mainSendButtonText: {
    color: colors.onAccent,
    fontSize: 16,
    lineHeight: 22,
    textAlign: 'center',
    fontFamily: fonts.ui,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  reviewCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
    padding: 16,
    borderRadius: 18,
    backgroundColor: colors.accentWash,
    borderWidth: 1,
    borderColor: colors.hairlineStrong,
    alignSelf: 'stretch',
  },
  reviewCopy: {
    flex: 1,
    gap: 4,
  },
  reviewTitle: {
    color: colors.text,
    fontSize: 18,
    lineHeight: 22,
    fontFamily: fonts.title,
  },
  reviewText: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: fonts.ui,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 16,
    marginBottom: 12,
  },
  detailLabel: {
    color: colors.textMuted,
    fontSize: 14,
    fontFamily: fonts.ui,
  },
  detailValueFlash: {
    alignSelf: 'flex-end',
    maxWidth: '100%',
  },
  detailValue: {
    color: colors.text,
    fontSize: 16,
    fontFamily: fonts.title,
    flexShrink: 1,
    textAlign: 'right',
  },
  availableFlash: {
    alignSelf: 'flex-start',
    maxWidth: '100%',
  },
  noticeCard: {
    backgroundColor: colors.surface,
  },
  noticeTitle: {
    color: colors.text,
    fontSize: 16,
    lineHeight: 20,
    fontFamily: fonts.title,
    marginBottom: 6,
  },
  noticeText: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: fonts.ui,
  },
  inlinePrimaryButton: {
    alignSelf: 'flex-start',
    backgroundColor: colors.accent,
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 12,
    marginTop: 4,
  },
  inlinePrimaryButtonText: {
    color: colors.onAccent,
    fontSize: 14,
    fontFamily: fonts.ui,
  },
  inputError: {
    borderColor: colors.error,
  },
  errorText: {
    color: colors.error,
    marginTop: 8,
  },
  warningText: {
    color: colors.warning,
    marginTop: 12,
  },
  });
}
